sudo: required
dist: trusty

language: go
go:
  - 1.9.2

install:
  - go get github.com/mattn/goveralls github.com/modocache/gover
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/jteeuwen/go-bindata/...
  - .travis-scripts/install-minikube.sh

before_script:
  - sudo minikube start --vm-driver=none --bootstrapper=localkube --kubernetes-version=$K8S_VERSION

script:
  - .travis-scripts/format.sh
  - hack/verify-codegen.sh
  - hack/verify-artifacts.sh
  - .travis-scripts/build.sh
  - .travis-scripts/build-cli.sh
  - .travis-scripts/test.sh
  - hack/e2e.sh -v $K8S_VERSION

after_script:
  - gover && goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN

deploy:
  - provider: script
    skip_cleanup: true
    script: .travis-scripts/deploy.sh
    on:
      branch: master

notifications:
  slack:
    secure: upd/2Bie4b+5IuRCCM5QAV/p4qVM9qYJSvW9uL7BgabA1lJJDeQ2//n0qJ4mFD85kpNyIJ0HTdFv2KB/bfNJ/14WsRqtFjtztbzENsi83YRkXqUQNJ2lug1CKRqrHNiJwAvhwE1MzI9yJbJP7jAkSacSTThtfZoQWO7m2qgcVfBWgbd9tsdbCJAEncFsGskNej4qOZFlZTAv6+6UaTPxZfEbsPR4NPoGQG+qxqH+eIrU7tUAM5equiVxSsPWKKnpSEafe30tEiIiqDjGINMghXtVfZHmjNtoFWSg560I/eHk3UcruJZDi8sEQ8LO9a1tZBe6HUERV0J0scvAai/pjcqfHPOHc0PajR25RtjOl7agjowkeP285AO8/Hq4waKjJNwuCN/UHsvr2W1lDzUF+LHggS5yngtr3KPa61taBnLtj15zDkFXKKSubL+GCbVdGG1U6ngOc0yEJRbvBBuWCIYksa3pIQla2sBdRjFgaIpzrTS6I/5eCdn9s3jzrxtYDDiUtbMSWB2nt11xV7npRbYOK3Rs28+6UV3Wg6Cd//g/klsI3wco+todZCUlMXGHLUe77780bhvdFenJ9Z44Ix14WXVo8NlQ0f9/QTOLP2/HPNRnZB8nz21TVcKkZpKTylzYA51expTvSiJ41lErHSRXV+/KCOW9za3i9CqLAmk=

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - K8S_VERSION=v1.10.0
    - MINIKUBE_VERSION=v0.27.0
    - KUBECONFIG=~/.kube/config
    - secure: EDlWAqoXL0z+RHkFMXB7Zox2IDogzgF4jE2OaVOX/IJIXIVMfWCgQElW2EIaK7tABYQoxtog+JltuUnfKZoIrA0M7lAtiwEagRBYyhGG6Z0uOsOEN8so8GYG4h7zNkY2VAIK/+4VAp2Fk7UMnswFZ0pQnGVTUpfcsvmyPIKYhMatZaSVrsC9Y7ycg6g9n1C3uK4Nir0RIJUi4ZSy2vmcc1rb3b040PhIEeiptc54jlphwO3a9lnoSrFk+4jebdA8HIwS63cE3xaBBLTBf8C6/vvuK1IbnWE4zmOTEqH7jXaCPYvyqWMpBeD30S8ZIlQOGP94rDdrLs1wehsl0jGzj+Lh08G7B1eY0zR/sdc8IpA7vlr631ERy/aXxXmSjXHutZGKJ+dPqYOav6XH2l7STyV+K6JiaTGJM1LOmxycjlwiMJdyWUw1PnADLmmJWhZjzWz4ZQa4hsuC3qEy0GOZ/0TgjgV3FyaRTYGBO//I6s1bzi1wbEwwfHxAo7o/zJPXFJuvH5m3zr0M1GGRQypHlXMLfP6/W3zUH7PbK2CIL8dd4QrWyMc+Xr4FDJrxjFBY1GQX5loj+7jYnYRFuPEMg8K1jw8CAP/qzkeDyS+ZmnzfOSvo/d3awwzyz4glRRa03yAE5jgWFZYDAkGDMtDr2KPoHf2GNoaXFeWL3Lvhzqs=
    - secure: UzhV0XlyZHnzZRwO7ygltrgmBkqATzR+sbx5d7DvVGazxJkbVKkMuh3/gj2y4MvBSHAlqe/dtGKDdmx3Lna24MCJA5zHpwehpLkeXKeZT3uBy2DKX4JEXKBZVRa3Cdhns7dKgcLqQ4pOJnB+Yx0leIlmwNQVZVjkPYzxVFO9O09Izt0m/e9iHEyM48RFFd0Ndn6JMRufyE+OubLAID3qnyxzXxQSNmoMO/sePBGzmJhHKAfUodSPIdnsLVv8IO0vRk7M5dnO8psJPhQ7JD9QFjYkMLFGwXbpYpYqxKa5YZTj23slAruSkEq0RXBppLOA4zxx1rXG5VsbNmskT7y8lQqrVlCQ4xWd0M+7Pd/hibuovK1UDngIcWS0ecHGR2gl0EFcDVYXtLWhmvLAkMyyo9ltPCBUW45aPp626wWZJry202QlRgGm/+zMS/Y7mt+6C1kounqoYjsb52MTyWmqMqdpB7MgmmaMiPSlwP+XCHLEC6Wk8qnm64P7ZaZlWY0EK96DGQ8RvaPC9I9fa7TZqZli+1Gt9JXsiwzR+7sOy1ChbWsKoGsqDc7oB910M6dCeiuWisD40aOxRX+9Uyn3Lb0hzj/CRwD/cInpPOqzcGikCvrxYMKRH+ER8uKV7Ctjp8NS50ideDC+HyYqP8cVbV/PLk1zxPCnN/GbtZPLgWY=
    - secure: lfCyVOivCvNSpNnDhyxTYp/SMmoJ7UlZuNN/K3Pnm7+MyEBzAn6PkK+AAViipodsL2rPyQ6hIxlgMJaOz1kWiR1vkGNcCLhx5/b2i71vVWM4jwkxYW04fcPZmMB5rWZgKDRS52Q6FWFXpuKRxWup0LJ/KQva2Jyj4epQXbXps0RfZjsyuLC1/WBzJmqGtaD21c5IyafkSsSUFn1liJyS5z0fDWcLZmlgkC3mmilBsXsK88s4EXJhvTS1uhCBm7UrNcpYciy8vIr9XamSeHKvY0Vf6bFaKQpWJCj9sCzvmCYkAdWmzfneINQToXmGh33ppuzu6xo/V0Q0JPUHq/07dh7ENRGeytUc4PaeBqsAZXl0nZbF+p5lWDW6D2ry1iXsL2CFN0qusb2LQk85dw+mwGn/f/Qc/maVIIyrFxT8OQI/1BwiM3mL2kouJJE5P+uwnfKOMDUgkBHj1VQTAe6oyleAgWqnbbUHchuduLuLuO7Yp3Z2VI5wNCvJnsL7BZUQTmczkFrQaCbeDbjRnWCY6bXgYVHIoQcbcCB8rCe9WAR2IOlnX6zPH+6FfSunPUTtFrSvnScRkPyADzpaJ2vfIaATn2sQBIYle1pUyXUyHpc5Hspko0GNRsXo/25JVa1T4zrYTmh/gAiN/fZCFLvKlFevoXO98DlP/2XwaUH2+I4=
    - secure: "eeeZg+v/Ya04wNPyJdbX+jWMmvLhSzKkToXdUmyKP6TrNHxHWewIj+i8vhdhcXYbMIvRsbUcWUdzQYkjVxskqfUkpwhi2/sksDStzqvEaYw/nBxfreHzFgFNQe61AoHKAD+BJhC8VqloGqCYhkCKKE0AswhGs4a4uO6ZlXc7bcFOn6K852CxYrMX1UN+nI/GoXR/Q5wq9QgXGiGr6IZRotPdLRpHFEOje+jFaQkEm7N5UcRyQ7pHEBIHiaj1uQ88oCKlxKjG9Ns4mrQi6z779j6LI76M9idNnPhICzyKNJSW4bPw1UEagg5YFDsJvfdFcHc2RVIEvy3VokZLC0zUJK4upHAInzspXnZWDFuf4awn9jb0RU4qfNineeNtMnDKtB+vQwzfIqRQ/FlgLjD9mrCXOQd1A6e3l6YPWA0A6G/48qxFLCC2RlD4I1Gv8yu3RVgC6x39aYXFEPw44RHvvfggBmks+wnmRdUppC7jiQTLQEs9CldUuQbB7KC2p+tyEvf0IM5+gWkAr/SYN662XpYdaz0RY6apIR1BFhlvwP11L+lsqP3F55r+F7xXsYv2LM1B5Gq8zU14YuRUJj//A7iM3bCmCffcKG9IQ2mj2tAVUTwlJSOXMXR4S3H6IBmI7Q7e1DJAnSI2rhkFnbZbQZxqv+C6Iys9Ph/nVvpjqDU="
