/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	cr_v1 "github.com/grtl/mysql-operator/pkg/apis/cr/v1"
	versioned "github.com/grtl/mysql-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/grtl/mysql-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/grtl/mysql-operator/pkg/client/listers/cr/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MySQLClusterInformer provides access to a shared informer and lister for
// MySQLClusters.
type MySQLClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MySQLClusterLister
}

type mySQLClusterInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewMySQLClusterInformer constructs a new informer for MySQLCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMySQLClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.CrV1().MySQLClusters(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.CrV1().MySQLClusters(namespace).Watch(options)
			},
		},
		&cr_v1.MySQLCluster{},
		resyncPeriod,
		indexers,
	)
}

func defaultMySQLClusterInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewMySQLClusterInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *mySQLClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cr_v1.MySQLCluster{}, defaultMySQLClusterInformer)
}

func (f *mySQLClusterInformer) Lister() v1.MySQLClusterLister {
	return v1.NewMySQLClusterLister(f.Informer().GetIndexer())
}
