apiVersion: cr.mysqloperator.grtl.github.com/v1
kind: MySQLCluster
metadata:
  name: my-cluster
spec:
  name: "my-cluster"
  port: "2222"
  user: "my-user"
  password: "my-password"
  database: "my-database"
