apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ CronJobName .Name }}
  ownerReferences:
    - kind: MySQLBackupSchedule
      apiVersion: cr.mysqloperator.grtl.github.com/v1
      name: {{ .Name }}
      uid: {{ .UID }}
spec:
  schedule: "{{ .Spec.Time }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: lachlanevenson/k8s-kubectl
            command:
            - sh
            - "-c"
            - |
              cat << EOF | kubectl create -f -
              apiVersion: cr.mysqloperator.grtl.github.com/v1
              kind: MySQLBackupInstance
              metadata:
                name: {{ BackupInstanceNamePrefix .Name }}-`date '+%Y-%m-%d-%H-%M-%S'`
                labels:
                  schedule: {{ .Name }}
                  cluster: {{ .Spec.Cluster }}
              spec:
                schedule: {{ .Name }}
                cluster: {{ .Spec.Cluster }}
              status:
                phase: Scheduled
              EOF
