apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Name }}-job
  ownerReferences:
    - kind: MySQLBackup
      apiVersion: cr.mysqloperator.grtl.github.com/v1
      name: {{ .Name }}
      uid: {{ .UID }}
spec:
  schedule: "{{ .Spec.Time }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: backup
            persistentVolumeClaim:
              claimName: {{ .Name }}
          - name: conf
            emptyDir: {}
          - name: config-map
            configMap:
              name: mysql
          containers:
          - name: backup
            image: grtl/xtrabackup:latest
            env:
            - name: JOB_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            command:
            - bash
            - "-c"
            - |
              set -ex

              # Clone data from master.
              mkdir /mysql/backup/{{ .Name }}/${JOB_NAME}
              ncat --recv-only {{ .Spec.Cluster }}-$((0)).{{ .Spec.Cluster }} 3307 | xbstream -x -C /mysql/backup/{{ .Name }}/${JOB_NAME}

              # Prepare the backup.
              xtrabackup --prepare --target-dir=mysql/backup/{{ .Name }}/${JOB_NAME}
            volumeMounts:
            - name: backup
              mountPath: /mysql/backup/{{ .Name }}
            - name: conf
              mountPath: /etc/mysql/conf.d
              resources:
                requests:
                  cpu: 100m
                  memory: 100Mi