apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqlbackupinstances.cr.mysqloperator.grtl.github.com
spec:
  group: cr.mysqloperator.grtl.github.com
  names:
    kind: MySQLBackupInstance
    listKind: MySQLBackupInstanceList
    singular: mysqlbackupinstance
    plural: mysqlbackupinstances
    shortNames:
    - mbi
    - mbis
  scope: Namespaced
  version: v1
